global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['kong-gateway:8100']
    scrape_interval: 5s
    metrics_path: '/metrics'
    scheme: 'http'
